#!/usr/bin/env python3
"""Verify the deployed GitHub Pages bytes against locally generated artifacts."""

from __future__ import annotations

import argparse
import json
import time
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
DEFAULT_URL = "https://kafka2306.github.io/bonus/"
BUILD_MARKER = b'name="bonus-build" content="verified-pages-v2"'


def fetch(url: str, attempts: int, delay: float) -> bytes:
    last_error: Exception | None = None
    request = urllib.request.Request(
        url,
        headers={"User-Agent": "KAFKA2306-bonus-live-audit/1.0"},
    )
    for attempt in range(1, attempts + 1):
        try:
            with urllib.request.urlopen(request, timeout=30) as response:
                if response.status != 200:
                    raise RuntimeError(f"HTTP {response.status}: {url}")
                return response.read()
        except (urllib.error.URLError, TimeoutError, RuntimeError) as exc:
            last_error = exc
            if attempt < attempts:
                time.sleep(delay)
    raise RuntimeError(f"failed after {attempts} attempts: {url}: {last_error}")


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--url", default=DEFAULT_URL)
    parser.add_argument("--attempts", type=int, default=12)
    parser.add_argument("--delay", type=float, default=5.0)
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    base = args.url.rstrip("/") + "/"
    expected_paths = {
        "styles.css": DOCS / "styles.css",
        "app.js": DOCS / "app.js",
        "data/bonus.json": DOCS / "data" / "bonus.json",
    }

    index = fetch(base, args.attempts, args.delay)
    if BUILD_MARKER not in index:
        raise SystemExit("live index.html does not contain verified-pages-v2 marker")
    if b"Bonus Evidence Atlas" not in index:
        raise SystemExit("live index.html does not contain the expected title")

    for relative_url, local_path in expected_paths.items():
        if not local_path.exists():
            raise SystemExit(f"local generated artifact is missing: {local_path}")
        live = fetch(base + relative_url, args.attempts, args.delay)
        expected = local_path.read_bytes()
        if live != expected:
            raise SystemExit(f"live artifact differs from generated bytes: {relative_url}")

    public = json.loads((DOCS / "data" / "bonus.json").read_text(encoding="utf-8"))
    if public.get("schema_version") != 1:
        raise SystemExit("unexpected public JSON schema version")
    if public.get("generated_from") != "data/verified_bonus_facts_2026-08-02.yaml":
        raise SystemExit("public JSON was not generated from the expected latest snapshot")

    print(
        "PASS: live Pages returned HTTP 200 and index/CSS/JS/JSON "
        "exactly match the verified build"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
