#!/usr/bin/env python3
"""Verify deployed Pages bytes against locally generated fact and hypothesis artifacts."""

from __future__ import annotations

import argparse
import hashlib
import json
import time
import urllib.error
import urllib.request
from pathlib import Path

from bonus_hypotheses import latest_hypothesis
from generate_verified_bonus_summary import DATA_DIR, latest_snapshot

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
DEFAULT_URL = "https://kafka2306.github.io/bonus/"
BUILD_MARKER = b'name="bonus-build" content="verified-pages-v3"'


def fetch(url: str, attempts: int, delay: float) -> bytes:
    last_error: Exception | None = None
    request = urllib.request.Request(
        url,
        headers={"User-Agent": "KAFKA2306-bonus-live-audit/1.0"},
    )
    for attempt in range(1, attempts + 1):
        try:
            with urllib.request.urlopen(request, timeout=30) as response:
                if response.status != 200:
                    raise RuntimeError(f"HTTP {response.status}: {url}")
                return response.read()
        except (urllib.error.URLError, TimeoutError, RuntimeError) as exc:
            last_error = exc
            if attempt < attempts:
                time.sleep(delay)
    raise RuntimeError(f"failed after {attempts} attempts: {url}: {last_error}")


def describe(body: bytes) -> str:
    preview = body[:800].decode("utf-8", errors="replace").replace("\n", " ")
    digest = hashlib.sha256(body).hexdigest()
    return f"bytes={len(body)} sha256={digest} preview={preview!r}"


def _relative_latest(selector, data_dir: Path, root: Path) -> str:
    snapshot = selector(data_dir).resolve()
    try:
        return str(snapshot.relative_to(root.resolve()))
    except ValueError:
        return str(snapshot)


def expected_generated_from(
    data_dir: Path = DATA_DIR,
    root: Path = ROOT,
) -> str:
    return _relative_latest(latest_snapshot, data_dir, root)


def expected_hypotheses_from(
    data_dir: Path = DATA_DIR,
    root: Path = ROOT,
) -> str:
    return _relative_latest(latest_hypothesis, data_dir, root)


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--url", default=DEFAULT_URL)
    parser.add_argument("--attempts", type=int, default=12)
    parser.add_argument("--delay", type=float, default=5.0)
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    base = args.url.rstrip("/") + "/"
    expected_paths = {
        "styles.css": DOCS / "styles.css",
        "app.js": DOCS / "app.js",
        "data/bonus.json": DOCS / "data" / "bonus.json",
    }

    index = fetch(base, args.attempts, args.delay)
    if BUILD_MARKER not in index:
        raise SystemExit(
            "live index.html does not contain verified-pages-v3 marker; "
            + describe(index)
        )
    if b"Bonus Evidence Atlas" not in index:
        raise SystemExit(
            "live index.html does not contain the expected title; " + describe(index)
        )

    for relative_url, local_path in expected_paths.items():
        if not local_path.exists():
            raise SystemExit(f"local generated artifact is missing: {local_path}")
        live = fetch(base + relative_url, args.attempts, args.delay)
        expected = local_path.read_bytes()
        if live != expected:
            raise SystemExit(
                f"live artifact differs from generated bytes: {relative_url}; "
                f"live={describe(live)} expected={describe(expected)}"
            )

    public = json.loads((DOCS / "data" / "bonus.json").read_text(encoding="utf-8"))
    if public.get("schema_version") != 1:
        raise SystemExit("unexpected public JSON schema version")

    expected_source = expected_generated_from()
    if public.get("generated_from") != expected_source:
        raise SystemExit(
            "public JSON was not generated from the latest verified snapshot: "
            f"expected={expected_source!r} actual={public.get('generated_from')!r}"
        )

    expected_hypotheses = expected_hypotheses_from()
    if public.get("hypotheses_generated_from") != expected_hypotheses:
        raise SystemExit(
            "public JSON was not generated from the latest hypothesis snapshot: "
            f"expected={expected_hypotheses!r} "
            f"actual={public.get('hypotheses_generated_from')!r}"
        )
    if public.get("summary", {}).get("hypothesis_count", 0) < 1:
        raise SystemExit("public JSON contains no hypotheses")

    print(
        "PASS: live Pages returned HTTP 200 and index/CSS/JS/JSON exactly match "
        "the verified facts plus hypothesis build"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
